---

language: python
python: 2.7
install:
  - pip install coveralls
before_script:
  - wget http://googleappengine.googlecode.com/files/google_appengine_1.8.9.zip -nv
  - unzip -q google_appengine_1.8.9.zip
script:
  - python testrunner.py `pwd`/google_appengine/
  - coverage report -m
after_success:
  coveralls --verbose
